name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Find all *.java files, compile all Java files, and run project
      run: cd src && find -name "*.java" > java_files.txt && javac @java_files.txt && ls && java -cp java Solution
    - name: Make manifest, find all *.class files, and make jar file
      run: ls && echo "Main-Class:Solution" > manifest.txt && find -name "*.class" > class_files.txt && jar cvfm PasswordVault.jar manifest.txt @class_files.txt